FROM alpine:3.22 AS test
COPY dufs /usr/local/bin/dufs
COPY assets /opt/dufs/assets
RUN chmod +x /usr/local/bin/dufs
EXPOSE 5000
VOLUME ["/data"]
ENTRYPOINT ["/usr/local/bin/dufs", "/data", "--assets", "/opt/dufs/assets"]
CMD ["--allow-all", "--bind", "0.0.0.0", "--port", "5000"]

FROM scratch AS final
COPY dufs /usr/local/bin/dufs
COPY assets /opt/dufs/assets
COPY --from=test /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
EXPOSE 5000
VOLUME ["/data"]
ENTRYPOINT ["/usr/local/bin/dufs", "/data", "--assets", "/opt/dufs/assets"]
CMD ["--allow-all", "--bind", "0.0.0.0", "--port", "5000"]
